- name: Change Hostname of Remote VMs
  hosts: all  # The group from your inventory in Semaphore
  become: true                # This allows running tasks with root privileges
  tasks:
    - name: Change Hostname
      ansible.builtin.hostname:
        name: "IND-STL-ANALYTICS-APP4"
      become: true
