- name: Change Hostname of Remote Machine
  hosts: all
  become: true
  become_user: administrator  # Replace with the sudo-enabled user's username
  tasks:
    - name: Update /etc/hostname
      lineinfile:
        path: /etc/hostname
        regexp: '^.*$'
        line: 'IND-STL-ANALYTICS-APP4'  # Replace with the new hostname you want to set
      notify:
        - Restart Hostname Service

  handlers:
    - name: Restart Hostname Service
      systemd:
        name: systemd-hostnamed
        state: restarted
