- name: Change Hostname of Remote VM
  hosts: all  # Replace with the appropriate host or group name
  become: true

  tasks:
    - name: Set new hostname
      ansible.builtin.hostname:
        name: IND-STL-ANALYTICS-APP3NEW  # Replace with the desired new hostname

    - name: Reboot for changes to take effect
      ansible.builtin.reboot:
        connect_timeout: 30
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: ansible_os_family == 'Debian'  # Adjust this condition based on your target OS family
