- name: Gather and Store System Info
  hosts: all
  gather_facts: yes

  tasks:
    - name: Gather system facts from remote node
      setup:

    - name: Store gathered facts locally
      local_action:
        module: copy
        content: |
          ansible_facts:
          hostname: {{ ansible_facts['hostname'] }}
        dest: ~/Desktop/ans/info.yaml
      delegate_to: localhost

