- name: Gather and Store Specific System Facts
  hosts: all
  gather_facts: yes
  tasks:
    - name: Display Facts
      debug:
        var: ansible_facts
    - name: Store Specific Facts in File
      set_fact:
        selected_facts:
          ip4address: "{{ ansible_default_ipv4.address }}"
          ip6address: "{{ ansible_default_ipv6.address }}"
          hostname: "{{ ansible_hostname }}"
    - name: Commit and Push Facts to Git Repository
      ansible.builtin.git:
        repo: https://github.com/Gracy-1/ansible-templates.git
        dest: master
        src: facts.json
        force: yes
