- name: Gather System Info and Store Locally
  hosts: all  # Replace with the appropriate host group or hostname
  gather_facts: yes
  
  tasks:
    - name: Gather system facts
      setup:
      
    - name: Store facts in a local file
      copy: content="{{ hostvars[inventory_hostname].ansible_facts }}" dest="/etc/ansible/{{ inventory_hostname }}_facts.json"
      delegate_to: localhost

