- name: Gather and Store Specific System Facts
  hosts: all
  gather_facts: yes
  tasks:
    - name: Debug Current User
      debug:
        var: ansible_user
    - name: Display Facts
      debug:
        var: ansible_facts
    - name: Store Specific Facts in File
      set_fact:
        selected_facts:
          all_ipv4_addresses: "{{ ansible_facts.all_ipv4_addresses }}"
          all_ipv6_addresses: "{{ ansible_facts.all_ipv6_addresses }}"
          hostname: "{{ ansible_facts.hostname }}"
    - name: Create Facts JSON File
      local_action:
        module: copy
        content: "{{ selected_facts | to_nice_json }}"
        dest: "/home/gracy/Documents/config-management/facts.json"
      ansible_user: administrator
      
