- name: Gather and Store System Info
  hosts: localhost  # This targets the local machine
  gather_facts: yes

  tasks:
    - name: Gather system facts from remote node
      setup:
      
    - name: Store gathered facts locally
      copy:  # Using the regular 'copy' module
        content: |
          ansible_facts:
            hostname: {{ ansible_facts['hostname'] }}
        dest: /home/gracy/Documents/config-management/info.yaml  # Update this path as needed
