- name: Gather and Store System Info
  hosts: all
  gather_facts: yes

  tasks:
    - name: Gather system facts from remote node
      setup:

    - name: Store gathered facts locally
      local_action:
        module: copy
        content: |
          ansible_facts:
          hostname: {{ ansible_facts['hostname'] }}
        dest: /tmp/systemInfo_bkp.yaml  # Update this path as needed

    - name: Display message about file creation
      debug:
        msg: "The systemInfo_bkp.yaml file has been created in /tmp/"
