---
- name: Gather and Store System Info
  hosts: all
  gather_facts: yes

  tasks:
    - name: Gather system facts from remote node
      setup:
        
    - name: Store gathered facts locally
      local_action:
        module: copy
        content: |
          ansible_facts:
            all_ipv4_addresses:
            {% for host in ansible_facts %}
              {% for ip in host.ansible_all_ipv4_addresses %}
              - {{ ip }}
              {% endfor %}
            {% endfor %}
            all_ipv6_addresses:
            {% for host in ansible_facts %}
              {% for ip in host.ansible_all_ipv6_addresses %}
              - {{ ip }}
              {% endfor %}
            {% endfor %}
          hostname: {{ ansible_facts['ansible_hostname'] }}
        dest: /home/gracy/Documents/config-management/systemInfo_bkp.yaml  # Update this path as needed
