- name: Gather and Store Specific System Facts
  hosts: my_vm
  gather_facts: yes
  tasks:
    - name: Display Facts
      debug:
        var: ansible_facts
    - name: Store Specific Facts in File
      set_fact:
        selected_facts:
          ip4address: "{{ ansible_default_ipv4.address }}"
          ip6address: "{{ ansible_default_ipv6.address }}"
          hostname: "{{ ansible_hostname }}"
          other_fact: "{{ ansible_facts.some_other_fact }}"
    - name: Commit and Push Facts to Git Repository
      ansible.builtin.git:
        repo: /path/to/your/git/repo
        dest: master
        src: facts.json
        force: yes
