- name: Gather and Store System Info
  hosts: all
  gather_facts: yes

  tasks:
    - name: Gather system facts from remote node
      setup:

    - name: Create destination directory if it doesn't exist
      local_action:
        module: file
        path: /root/etc
        state: directory

    - name: Store gathered facts locally
      local_action:
        module: copy
        content: |
          ansible_facts:
            hostname: {{ ansible_facts['hostname'] }}
        dest: /root/etc/info.txt
      delegate_to: localhost
