- name: Gather and Store Specific System Facts
  hosts: all
  gather_facts: yes
  tasks:
    - name: Display Facts
      debug:
        var: ansible_facts
    - name: Store Specific Facts in File
      set_fact:
        selected_facts:
          all_ipv4_addresses: "{{ ansible_facts.all_ipv4_addresses }}"
          all_ipv6_addresses: "{{ ansible_facts.all_ipv6_addresses }}"
          hostname: "{{ ansible_facts.hostname }}"
      delegate_to: localhost
    - name: Create Facts JSON File
      local_action: copy content="{{ selected_facts | to_nice_json }}" dest="./facts.json"
      delegate_to: localhost
    - name: Commit and Push Facts to Git Repository
      delegate_to: localhost
      run_once: true
      become: false
      command: >
        bash -c "cd /path/to/your/git/repo &&
                 git add facts.json &&
                 git commit -m 'Update facts' &&
                 git push origin master"
